// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AgDbContext))]
    [Migration("20251124121617_UpdateDestinationConfigUniqueIndex")]
    partial class UpdateDestinationConfigUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityBooked", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityBooked");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            ActivityId = 1
                        },
                        new
                        {
                            BookId = 1,
                            ActivityId = 2
                        },
                        new
                        {
                            BookId = 2,
                            ActivityId = 3
                        });
                });

            modelBuilder.Entity("Domaine.Model.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Activity");

                    b.HasIndex("DestinationId");

                    b.ToTable("Activities", t =>
                        {
                            t.HasCheckConstraint("CK_Activity__Price", "[price] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Découvre les monuments les plus célèbres sur visible depuis le bord de la Seine...",
                            DestinationId = 2,
                            Price = 45m,
                            Title = "Visite de Paris en Bateau la nuit"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Découvre les monuments tranquillement depuis nos bus a deux étages...",
                            DestinationId = 2,
                            Price = 35m,
                            Title = "Visite de Paris en Bus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Avec notre guide découvrez l'histoire de cette villes...",
                            DestinationId = 1,
                            Price = 60m,
                            Title = "Visite de Bruxelles"
                        });
                });

            modelBuilder.Entity("Domaine.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Booking");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookind_Date", "[BookingDate] >= GetDate()");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2
                        });
                });

            modelBuilder.Entity("Domaine.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Customer");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Durant"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dupont"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Smith"
                        });
                });

            modelBuilder.Entity("Domaine.Model.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Destination");

                    b.HasIndex("Country", "City")
                        .IsUnique()
                        .HasDatabaseName("IX_Destination_Country_City");

                    b.ToTable("Destinations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Bruxelles",
                            Country = "Belgique",
                            Description = "Découvrez le plat pays a travers nos activité"
                        },
                        new
                        {
                            Id = 2,
                            City = "Paris",
                            Country = "France",
                            Description = "Voyagez a travers nos régions..."
                        });
                });

            modelBuilder.Entity("ActivityBooked", b =>
                {
                    b.HasOne("Domaine.Model.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domaine.Model.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domaine.Model.Activity", b =>
                {
                    b.HasOne("Domaine.Model.Destination", "Destination")
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Domaine.Model.Booking", b =>
                {
                    b.HasOne("Domaine.Model.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domaine.Model.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Domaine.Model.Destination", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
