// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AgDbContext))]
    [Migration("20251119131122_CreationActivity_Class_Config_Seed1")]
    partial class CreationActivity_Class_Config_Seed1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domaine.Model.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Activity");

                    b.ToTable("Activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activity__Price", "[price] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Découvre les monuments les plus célèbres sur visible depuis le bord de la Seine...",
                            Price = 45m,
                            Title = "Visite de Paris en Bateau la nuit"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Découvre les monuments tranquillement depuis nos bus a deux étages...",
                            Price = 35m,
                            Title = "Visite de Paris en Bus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Avec notre guide découvrez l'histoire de cette villes...",
                            Price = 60m,
                            Title = "Visite de Bruxelles"
                        });
                });

            modelBuilder.Entity("Domaine.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Customer");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Durant"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dupont"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Smith"
                        });
                });

            modelBuilder.Entity("Domaine.Model.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Destination");

                    b.HasIndex("Country")
                        .IsUnique();

                    b.ToTable("Destinations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Bruxelles",
                            Country = "Belgique",
                            Description = "Découvrez le plat pays a travers nos activité"
                        },
                        new
                        {
                            Id = 2,
                            City = "Paris",
                            Country = "France",
                            Description = "Voyagez a travers nos régions..."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
